# Generated by Django 5.2.6 on 2025-11-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_sales_rep',
            field=models.BooleanField(blank=True, default=False, help_text='If True, it would get commissions per sale'),
        ),
    ]
