# Generated by Django 5.2.6 on 2025-09-21 16:32

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Primary email for communication', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='e.g., +593-99-123-4567', max_length=20)),
                ('website', models.URLField(blank=True, help_text="Partner's website, if available")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='Name of the partner company', max_length=200, unique=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the partner')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the partner')),
                ('contact_person', models.CharField(blank=True, help_text='Main contact person', max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='partners.partner')),
            ],
            options={
                'verbose_name': 'partner Translation',
                'db_table': 'partners_partner_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
