# Generated by Django 5.2.6 on 2026-01-21 20:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlannerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('route_name', models.CharField(blank=True, max_length=255)),
                ('waypoints', models.JSONField(blank=True, default=list, help_text="List of dicts: [{'name': 'Cuenca Cathedral', 'lat': -2.8974, 'lng': -79.0045}, ...]")),
                ('route_summary', models.JSONField(blank=True, default=dict, help_text="{'total_distance_km': 123.4, 'total_duration_min': 180, 'segments': [...]}")),
                ('notes', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Route Planner',
            },
            bases=('wagtailcore.page',),
        ),
    ]
