# Generated by Django 5.2.6 on 2026-01-21 20:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Cuenca → Ingapirca via Cañar'", max_length=255)),
                ('waypoints', models.JSONField(blank=True, default=list)),
                ('route_summary', models.JSONField(blank=True, default=dict)),
                ('notes', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Planned Route',
                'verbose_name_plural': 'Planned Routes',
            },
        ),
        migrations.AlterModelOptions(
            name='routeplannerpage',
            options={'verbose_name': 'Route Planner Tool'},
        ),
        migrations.RemoveField(
            model_name='routeplannerpage',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='routeplannerpage',
            name='route_name',
        ),
        migrations.RemoveField(
            model_name='routeplannerpage',
            name='route_summary',
        ),
        migrations.RemoveField(
            model_name='routeplannerpage',
            name='waypoints',
        ),
    ]
