# Generated by Django 5.2.6 on 2026-01-22 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routify', '0002_plannedroute_alter_routeplannerpage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedroute',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created the reservation. Defaults to MTWEB for non-authenticated users.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
