# Generated by Django 5.2.6 on 2025-09-23 01:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToursIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Introduction for the tours index page')),
            ],
            options={
                'verbose_name': 'Tours Index',
                'verbose_name_plural': 'Tours Indices',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LandTourPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(help_text="e.g., 'Cuenca Cultural Getaway'", max_length=200)),
                ('destination', models.CharField(choices=[('Ecuador', 'Ecuador'), ('Other', 'Other')], default='Ecuador', help_text='Select the destination country.', max_length=100)),
                ('description', models.TextField(help_text='Description of the land tour.')),
                ('location', models.CharField(help_text='Location inside the country', max_length=30)),
                ('cover_page_content', models.TextField(blank=True, help_text="Content for the tour's cover page.")),
                ('general_info', models.TextField(blank=True, help_text='General info like cancellation policy, inclusions.')),
                ('final_message', models.TextField(blank=True, help_text='Final message from the travel company.')),
                ('courtesies', models.TextField(blank=True, default='Tour guiado por la ciudad', help_text='Tour inclusions')),
                ('no_inclusions', models.TextField(blank=True, default='Ticket aéreo', help_text='Not included')),
                ('additional_notes', models.TextField(blank=True, default='Sujeto a disponibilidad. Consultar suplementos para festivos.')),
                ('hotel', models.CharField(default='LOCAL', max_length=50)),
                ('is_on_discount', models.BooleanField(default=False)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('is_special_offer', models.BooleanField(default=False)),
                ('is_all_inclusive', models.BooleanField(default=False)),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('code_id', models.CharField(editable=False, max_length=9, unique=True)),
                ('pdf_images', models.JSONField(blank=True, default=list, help_text='List of URLs for PDF page images')),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('nights', models.PositiveIntegerField(default=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_days', models.CharField(blank=True, default='', help_text="Comma-separated days (0=Sunday, ..., 6=Saturday), e.g., '0,1,2,3'", max_length=50)),
                ('supplier_email', models.EmailField(blank=True, help_text='Supplier contact email', max_length=254)),
                ('pricing_type', models.CharField(choices=[('per_room', 'Per Room'), ('per_person', 'Per Person')], default='per_room', max_length=20)),
                ('max_children_per_room', models.PositiveIntegerField(default=1)),
                ('child_age_min', models.PositiveIntegerField(default=7)),
                ('child_age_max', models.PositiveIntegerField(default=12)),
                ('price_sgl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_dbl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_tpl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_chd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_inf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seasonal_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('demand_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rep_comm', models.PositiveIntegerField(default=0, help_text='Sales representative commission')),
                ('yt_vid', models.URLField(default='www.none.com', help_text='This video will be shown in the Tours Watch Video.')),
                ('max_capacity', models.PositiveIntegerField(default=20)),
                ('available_slots', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', wagtail.fields.StreamField([('day', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g., 'Day 1'", 'label': 'Day Number'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Description'}), 2: ('wagtail.blocks.StructBlock', [[('day_number', 0), ('description', 1)]], {})}, help_text='Itinerary for the tour')),
                ('cover_image', models.ForeignKey(blank=True, help_text="Image for the tour's cover page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_tour_cover', to='wagtailimages.image')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_tours_image', to='wagtailimages.image')),
                ('logo_image', models.ForeignKey(blank=True, help_text='Company logo for the final page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_tour_logo', to='wagtailimages.image')),
                ('pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_tours_pdf', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Land Tour',
                'verbose_name_plural': 'Land Tours',
            },
            bases=('wagtailcore.page',),
        ),
    ]
