# Generated by Django 5.2.6 on 2025-09-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='code_id',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
