# Generated by Django 5.2.6 on 2025-11-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='available_days',
            field=models.CharField(blank=True, default='', help_text="Comma-separated days (0=Sunday, 1=Monday..., 6=Saturday), e.g., '0,1,2,3'", max_length=50),
        ),
    ]
