# Generated by Django 5.2.6 on 2025-10-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='is_company_tour',
            field=models.BooleanField(default=False, help_text='If True, skip supplier confirmation and go direct to payment (company-run tour).'),
        ),
    ]
