# Generated by Django 5.2.6 on 2025-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_landtourpage_is_company_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='price_adult',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
