# Generated by Django 5.2.6 on 2025-11-11 20:11

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_landtourpage_available_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='additional_notes',
            field=models.TextField(blank=True, default='Subject to availability'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='child_age_max',
            field=models.PositiveIntegerField(default=12, verbose_name='Child Maximum Age'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='child_age_min',
            field=models.PositiveIntegerField(default=7, verbose_name='Child Minimum Age'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='courtesies',
            field=models.TextField(blank=True, default='Guided city tour', help_text='Tour inclusions'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='cover_page_content',
            field=models.TextField(blank=True, help_text="Content for the tour's cover page in the PDF Generator."),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='demand_factor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The Demand Factor will increase price based on the total occupancy calculated for the next 30 days (counting the selected travel date). 0 = 0%. If 20%, this means the first booking will have an increased value of 0, and the last one 20%', max_digits=3, verbose_name='Demand Factor'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='final_message',
            field=models.TextField(blank=True, help_text='Final message from the travel company in the PDF Generator. '),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='general_info',
            field=models.TextField(blank=True, help_text='General info like cancellation policy, inclusions in the PDF Generator.'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='max_capacity',
            field=models.PositiveIntegerField(default=20, help_text='Maximum Capacity is taken to calculate price increased based on the demand factor'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='max_children_per_room',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='no_inclusions',
            field=models.TextField(blank=True, default='Air Ticket', help_text='Not included'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='price_adult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Adults Price'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='price_chd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Children Price'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='price_dbl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Double Room Price'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='price_inf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Infant Price'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='price_sgl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Single Room Price'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='price_tpl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Triple Room Price'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='seasonal_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='1.0 = 0%. This will increase the price on certain seasons of the year like holidays', max_digits=3, verbose_name='Seasonal Price Factor increase'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='yt_vid',
            field=models.URLField(default='www.none.com', help_text='This video will be shown in the Tours Watch Video.', verbose_name='Youtube Video'),
        ),
        migrations.AlterField(
            model_name='toursindexpage',
            name='body_content',
            field=wagtail.fields.StreamField([('text_band', 5), ('flex_images', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 36, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('--cyan-60', 'Sky Blue'), ('--cyan-10', 'Cyan'), ('--cyan-dark-70', 'Dark Cyan'), ('--yellow-dark-30', 'Sand'), ('--yellow-0', 'Yellow'), ('--yellow-dark-40', 'Dark Yellow'), ('--yellow-dark-70', 'Brown'), ('--red-10', 'Red'), ('--red-dark-20', 'Red Blood'), ('--red-dark-60', 'Dark Red'), ('--red-50', 'Pink'), ('--green2-10', 'Green'), ('--green2-dark-70', 'Dark Green'), ('--yellow-dark-100', 'Black'), ('gray', 'Gray'), ('--yellow-100', 'White')]}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'If checked, all social links configured in admin/settings will render.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('band_title', 0), ('textbox_1', 1), ('textbox_2', 1), ('background_image', 2), ('background_color', 3), ('social_media_icon', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Image caption', 'max_length': 300, 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('image_caption', 9)]], {})}, null=True),
        ),
    ]
