# Generated by Django 5.2.6 on 2025-10-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_landtourpage_code_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toursindexpage',
            options={'verbose_name': 'Tours List Page', 'verbose_name_plural': 'Tours Indices'},
        ),
    ]
