# Generated by Django 5.2.6 on 2025-10-06 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_toursindexpage_options'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text="Image for the tour's cover page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cover', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='description',
            field=models.TextField(help_text='Description of the tour.'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='destination',
            field=models.CharField(choices=[('Dominican Republic', 'Dominican Republic'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Iceland', 'Iceland'), ('Poland', 'Poland')], default='Ecuador', help_text='Select the destination country.', max_length=100),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_image', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='logo_image',
            field=models.ForeignKey(blank=True, help_text='Company logo for the final page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_logo', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_pdf', to='wagtaildocs.document'),
        ),
    ]
