# Generated by Django 5.2.6 on 2025-11-12 03:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_landtourpage_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='cxl_policies',
            field=wagtail.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='additional_notes',
            field=wagtail.fields.RichTextField(blank=True, default='Subject to availability'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='courtesies',
            field=wagtail.fields.RichTextField(blank=True, default='Guided city tour', help_text='Tour inclusions'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='cover_page_content',
            field=wagtail.fields.RichTextField(blank=True, help_text="Content for the tour's cover page in the PDF Generator."),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='description',
            field=wagtail.fields.RichTextField(help_text='Description of the tour.'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='final_message',
            field=wagtail.fields.RichTextField(blank=True, help_text='Final message from the travel company in the PDF Generator. '),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='general_info',
            field=wagtail.fields.RichTextField(blank=True, help_text='General info like cancellation policy, inclusions in the PDF Generator.'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='no_inclusions',
            field=wagtail.fields.RichTextField(blank=True, default='Air Ticket', help_text='Not included'),
        ),
    ]
