# Generated by Django 5.2.6 on 2025-10-06 22:22

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_landtourpage_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='code_id',
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='itinerary',
            field=wagtail.fields.StreamField([('day', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g., 'Day 1'", 'label': 'Day Number'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description'}), 2: ('wagtail.blocks.StructBlock', [[('day_number', 0), ('description', 1)]], {})}, help_text='Itinerary for the tour'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
