# Generated by Django 5.2.6 on 2025-11-12 17:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_landtourpage_cxl_policies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landtourpage",
            name="code_id",
            field=models.CharField(
                editable=False,
                help_text="This is the Tours unique internal ID. Other companies might use this code as reference. Without this ID, it would be impossible to render the tours.",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="landtourpage",
            name="cxl_policies",
            field=wagtail.fields.RichTextField(
                blank=True, default="", null=True, verbose_name="Cancellation Policies"
            ),
        ),
        migrations.AlterField(
            model_name="landtourpage",
            name="hotel",
            field=models.CharField(
                default="LOCAL", help_text="If applicable", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="landtourpage",
            name="itinerary",
            field=wagtail.fields.StreamField(
                [("day_entry", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Day description", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"max_chars": 300, "required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("day", 0), ("description", 1), ("highlight", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="landtourpage",
            name="ref_code",
            field=models.CharField(
                blank=True,
                help_text="This is the Referal Code. This is used for referencing a third party tour. Most of the time,\n        large tour operators have their own tour code, so this field can be used to reference by that code so it is easy to find it in large databases.\n                ",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="landtourpage",
            name="supplier_email",
            field=models.EmailField(
                blank=True,
                help_text="Supplier contact email. If This is a in House/company tour, check the next box and skip this email field.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="toursindexpage",
            name="body_content",
            field=wagtail.fields.StreamField(
                [("text_band", 5), ("flex_images", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 36, "required": False},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("--cyan-60", "Sky Blue"),
                                ("--cyan-10", "Cyan"),
                                ("--cyan-dark-70", "Dark Cyan"),
                                ("--yellow-dark-30", "Sand"),
                                ("--yellow-0", "Yellow"),
                                ("--yellow-dark-40", "Dark Yellow"),
                                ("--yellow-dark-70", "Brown"),
                                ("--red-10", "Red"),
                                ("--red-dark-20", "Red Blood"),
                                ("--red-dark-60", "Dark Red"),
                                ("--red-50", "Pink"),
                                ("--green2-10", "Green"),
                                ("--green2-dark-70", "Dark Green"),
                                ("--yellow-dark-100", "Black"),
                                ("gray", "Gray"),
                                ("--yellow-100", "White"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If checked, all social links configured in admin/settings will render.",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("band_title", 0),
                                ("textbox_1", 1),
                                ("textbox_2", 1),
                                ("background_image", 2),
                                ("background_color", 3),
                                ("social_media_icon", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption",
                            "max_length": 300,
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 6), ("caption", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: ("wagtail.blocks.StructBlock", [[("image_caption", 9)]], {}),
                },
                null=True,
            ),
        ),
    ]
