# Generated by Django 5.2.6 on 2025-11-14 16:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_landtourpage_code_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='description_content',
            field=wagtail.fields.StreamField([('swipers', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The main title.', 'max_length': 33, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'max_length': 40, 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link for the image. If provided, the image will be clickable.', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('basic', 'Basic Swiper'), ('framed', 'Framed Pictures'), ('thumbnail', 'With Thumbnail Navigation')]}), 7: ('wagtail.blocks.StructBlock', [[('swiper_title', 0), ('images', 5), ('variations', 6)]], {})}, help_text='\n        This content will only be added inside the description content\n        ', null=True),
        ),
    ]
