# Generated by Django 5.2.6 on 2025-10-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_landtourpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtourpage',
            name='content',
        ),
    ]
