# Generated by Django 5.2.6 on 2025-10-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_landtourpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='amenities',
            field=models.CharField(blank=True, choices=[('fa-swimming-pool', 'Swimming Pool'), ('fa-wifi', 'Free WiFi'), ('fa-parking', 'Parking'), ('fa-spa', 'Spa'), ('fa-utensils', 'Restaurant')], help_text='Add up to 5 amenities.', null=True),
        ),
        migrations.AddField(
            model_name='landtourpage',
            name='price_subtext',
            field=models.CharField(default='Estimated', help_text='Estimated. IVA not included', max_length=30),
        ),
    ]
