# Generated by Django 5.2.6 on 2025-10-16 14:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_landtourpage_amenities_landtourpage_price_subtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='amenity',
            field=wagtail.fields.StreamField([('include', 0)], blank=True, block_lookup={0: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('fa-swimming-pool', 'Swimming Pool'), ('fa-wifi', 'Free WiFi'), ('fa-parking', 'Parking'), ('fa-spa', 'Spa'), ('fa-utensils', 'Restaurant')]})}, help_text='Itinerary for the tour'),
        ),
    ]
