# Generated by Django 5.2.6 on 2025-11-17 16:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_landtourpage_blackout_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtourpage',
            name='blackout_dates',
        ),
        migrations.AddField(
            model_name='landtourpage',
            name='blackout_entries',
            field=wagtail.fields.StreamField([('single_date', 0), ('date_range', 3)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {'help_text': 'One specific date to disable.', 'label': 'Single Blackout Date'}), 1: ('wagtail.blocks.DateBlock', (), {'label': 'Start Date', 'required': True}), 2: ('wagtail.blocks.DateBlock', (), {'help_text': 'Inclusive end date.', 'label': 'End Date', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('start_date', 1), ('end_date', 2)]], {'icon': 'date', 'label': 'Blackout Date Range'})}, help_text='Add single blackout dates or ranges (e.g., holidays).'),
        ),
    ]
