# Generated by Django 5.2.6 on 2025-10-21 01:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_landtourpage_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtourpage',
            name='amenities',
        ),
        migrations.AddField(
            model_name='toursindexpage',
            name='body_content',
            field=wagtail.fields.StreamField([('text_band', 4), ('flex_images', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 36, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('--cyan-dark-10', 'Cyan'), ('--yellow-dark-20', 'Yellow'), ('--red-dark-10', 'Red'), ('--green2-dark-20', 'Green'), ('--yellow-dark-100', 'Black')]}), 4: ('wagtail.blocks.StructBlock', [[('band_title', 0), ('textbox_1', 1), ('textbox_2', 1), ('background_image', 2), ('background_color', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='amenity',
            field=wagtail.fields.StreamField([('include', 1)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-concierge-bell', '24-Hour Front Desk'), ('fa-wheelchair', 'Accessibility Features'), ('fa-snowflake', 'Air Conditioning'), ('fa-shuttle-van', 'Airport Shuttle'), ('fa-glass-martini', 'Bar'), ('fa-bath', 'Bathtub'), ('fa-water', 'Beach Access'), ('fa-umbrella-beach', 'Beach Umbrellas'), ('fa-bicycle', 'Bicycle Rental'), ('fa-coffee', 'Breakfast Included'), ('fa-laptop', 'Business Center'), ('fa-car', 'Car Rental'), ('fa-bed', 'Comfortable Beds'), ('fa-concierge-bell', 'Concierge Service'), ('fa-briefcase', 'Conference Rooms'), ('fa-leaf', 'Eco-Friendly'), ('fa-plug', 'Electric Vehicle Charging'), ('fa-theater-masks', 'Entertainment Shows'), ('fa-child', 'Family Friendly'), ('fa-fish', 'Fishing'), ('fa-dumbbell', 'Fitness Center'), ('fa-wifi', 'Free WiFi'), ('fa-tree', 'Garden'), ('fa-shopping-bag', 'Gift Shop'), ('fa-golf-ball', 'Golf Course'), ('fa-map', 'Guided Tours'), ('fa-hiking', 'Hiking Trails'), ('fa-horse', 'Horseback Riding'), ('fa-hot-tub', 'Hot Tub'), ('fa-tv', 'In-Room TV'), ('fa-tshirt', 'Laundry Service'), ('fa-spa', 'Massage Services'), ('fa-smoking-ban', 'Non-Smoking Rooms'), ('fa-sun', 'Outdoor Terrace'), ('fa-parking', 'Parking'), ('fa-paw', 'Pet Friendly'), ('fa-camera', 'Photography Tours'), ('fa-umbrella', 'Poolside Bar'), ('fa-shower', 'Private Bathroom'), ('fa-bus', 'Public Transport Access'), ('fa-utensils', 'Restaurant'), ('fa-bell', 'Room Service'), ('fa-lock', 'Safe Deposit Box'), ('fa-binoculars', 'Sightseeing Tours'), ('fa-smoking', 'Smoking Area'), ('fa-spa', 'Spa'), ('fa-sun', 'Sun Deck'), ('fa-swimming-pool', 'Swimming Pool'), ('fa-taxi', 'Taxi Service'), ('fa-wine-glass', 'Wine Tasting')]}), 1: ('wagtail.blocks.ListBlock', (0,), {})}, help_text='Add as many amenities.'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='itinerary',
            field=wagtail.fields.StreamField([('day_entry', 3)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Day description', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'max_chars': 300, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('day', 0), ('description', 1), ('highlight', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='pricing_type',
            field=models.CharField(choices=[('Per_room', 'Per Room'), ('Per_person', 'Per Person')], default='Per_person', max_length=20),
        ),
    ]
