# Generated by Django 5.2.6 on 2025-11-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_landtourpage_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='pricing_type',
            field=models.CharField(choices=[('Per_room', 'Per Room'), ('Per_person', 'Per Person'), ('Combined', 'Combined price')], default='Per_person', max_length=20),
        ),
    ]
