# Generated by Django 5.2.6 on 2025-11-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_landtourpage_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='pricing_type',
            field=models.CharField(choices=[('Per_room', 'Per Room (classic hotel-style)'), ('Per_person', 'Per Person (flat rate, no room logic)'), ('Combined', 'Combined (Per-person base + room sharing discount) — Most common')], default='Combined', help_text='Combined = adult pays base price, gets discount when sharing room. Best for private tours.', max_length=20),
        ),
    ]
