# Generated by Django 5.2.6 on 2025-11-18 05:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_alter_landtourpage_pricing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='combined_pricing_tiers',
            field=wagtail.fields.StreamField([('tier', 6)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum number of adults (inclusive)', 'required': True}), 1: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of adults (inclusive). Leave empty for 16+', 'required': False}), 2: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'help_text': 'Base price per adult', 'required': True}), 3: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': 0, 'help_text': 'Extra charge for single room (on top of adult price)'}), 4: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': 0, 'help_text': 'Discount per person when sharing double (e.g. 200 = –$200)'}), 5: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': 0, 'help_text': 'Discount per person when sharing triple'}), 6: ('wagtail.blocks.StructBlock', [[('min_pax', 0), ('max_pax', 1), ('price_adult', 2), ('price_sgl_supplement', 3), ('price_dbl_discount', 4), ('price_tpl_discount', 5)]], {})}, help_text='Tiered pricing for Combined mode. Ordered from smallest to largest group.', null=True),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='pricing_type',
            field=models.CharField(choices=[('Per_room', 'Per Room (classic hotel-style)'), ('Per_person', 'Per Person (flat rate, no room logic)'), ('Combined', 'Combined (Tiered)')], default='Combined', help_text='Combined = adult pays base price, gets discount when sharing room. Best for private tours.', max_length=20),
        ),
    ]
