# Generated by Django 5.2.6 on 2025-11-18 16:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_alter_landtourpage_combined_pricing_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='combined_pricing_tiers',
            field=wagtail.fields.StreamField([('tier', 10)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Minimum number of adults (inclusive)', 'required': True}), 1: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Maximum number of adults (inclusive)', 'required': False}), 2: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'help_text': 'Base price per adult', 'required': True}), 3: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': 0, 'help_text': 'Extra charge for single room (on top of adult price)'}), 4: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': 0, 'help_text': 'Discount per person when sharing double (e.g. 200 = –$200)'}), 5: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': 0, 'help_text': 'Discount per person when sharing triple'}), 6: ('wagtail.blocks.FloatBlock', (), {'default': 60.0, 'help_text': 'Child price as % of adult base price (e.g. 60 = 60%)', 'max_value': 100, 'min_value': 0}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('free', 'Free (0–2 years)'), ('percent', 'Percentage of adult price'), ('fixed', 'Fixed amount per infant')], 'help_text': 'How should infants be charged?'}), 8: ('wagtail.blocks.FloatBlock', (), {'default': 10.0, 'help_text': "Only used if 'Percentage of adult price' is selected", 'max_value': 100, 'min_value': 0, 'required': False}), 9: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': 0, 'help_text': "Only used if 'Fixed amount' is selected", 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('min_pax', 0), ('max_pax', 1), ('price_adult', 2), ('price_sgl_supplement', 3), ('price_dbl_discount', 4), ('price_tpl_discount', 5), ('child_price_percent', 6), ('infant_price_type', 7), ('infant_percent_of_adult', 8), ('infant_fixed_amount', 9)]], {})}, help_text='Tiered pricing for Combined mode. Ordered from smallest to largest group.', null=True, verbose_name='Combined Pricing Tiers (by Group Size)'),
        ),
    ]
