# Generated by Django 5.2.6 on 2025-11-18 17:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_alter_landtourpage_combined_pricing_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='show_prices_in_table',
            field=wagtail.fields.RichTextField(default='Message to be shown instead of the pricing table in the tours detail page.', help_text='Message to be shown instead of the pricing table in the tours detail page.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='combined_pricing_tiers',
            field=wagtail.fields.StreamField([('tier', 8)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'required': True}), 1: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Do not leave it empty', 'required': True}), 2: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'required': True}), 3: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': 0}), 4: ('wagtail.blocks.FloatBlock', (), {'default': 60.0, 'max_value': 100, 'min_value': 0}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('free', 'Free'), ('percent', 'Percentage of adult price'), ('fixed', 'Fixed amount per infant')]}), 6: ('wagtail.blocks.FloatBlock', (), {'default': 10.0, 'max_value': 100, 'min_value': 0, 'required': False}), 7: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'default': 0, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('min_pax', 0), ('max_pax', 1), ('price_adult', 2), ('price_sgl_supplement', 3), ('price_dbl_discount', 3), ('price_tpl_discount', 3), ('child_price_percent', 4), ('infant_price_type', 5), ('infant_percent_of_adult', 6), ('infant_fixed_amount', 7)]], {})}, help_text='Tiered pricing for Combined mode. Ordered from smallest to largest group.', null=True, verbose_name='Combined Pricing Tiers (by Group Size)'),
        ),
    ]
