# Generated by Django 5.2.6 on 2025-11-18 17:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_landtourpage_show_prices_in_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='show_prices_in_table',
            field=wagtail.fields.RichTextField(blank=True, help_text='If filled, replaces the entire pricing table with this message in the Tours Detail page.', null=True),
        ),
    ]
