# Generated by Django 5.2.6 on 2025-11-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_alter_landtourpage_show_prices_in_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='button_link',
            field=models.URLField(blank=True, help_text='Where do you want to send the user? Link the button.', null=True),
        ),
        migrations.AddField(
            model_name='landtourpage',
            name='button_text',
            field=models.CharField(blank=True, default='', help_text='Text to be shown on the button', max_length=22, null=True, verbose_name='Button Text'),
        ),
    ]
