# Generated by Django 5.2.6 on 2025-11-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_landtourpage_button_link_landtourpage_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='pricing_table',
            field=models.BooleanField(default=False, verbose_name='Enable Pricing Table in Tour Details'),
        ),
    ]
