# Generated by Django 5.2.6 on 2025-11-21 16:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_alter_toursindexpage_body_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='disclaimer',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='For example: All prices are subject to availability', null=True, verbose_name='Disclaimer Message (Tours Details)'),
        ),
    ]
