# Generated by Django 5.2.6 on 2025-11-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_landtourpage_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='yt_vid',
            field=models.URLField(default='UHLdLtEiFGs', help_text='For example: https://www.youtube.com/watch?v=UHLdLtEiFGs >> ID = UHLdLtEiFGs. This video will be shown in the Tours Watch Video.', verbose_name='Youtube Video ID'),
        ),
    ]
