# Generated by Django 5.2.6 on 2025-11-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0023_alter_landtourpage_yt_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtourpage',
            name='yt_vid',
            field=models.CharField(default='UHLdLtEiFGs', help_text='For example: https://www.youtube.com/watch?v=UHLdLtEiFGs >> ID = UHLdLtEiFGs. This video will be shown in the Tours Watch Video.', verbose_name='Youtube Video ID'),
        ),
    ]
