# Generated by Django 5.2.6 on 2025-11-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('tours', '0025_alter_landtourpage_amenity_daytourpage_fulltourpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytourpage',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_pdf', to='documents.customdocument'),
        ),
        migrations.AlterField(
            model_name='fulltourpage',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_pdf', to='documents.customdocument'),
        ),
        migrations.AlterField(
            model_name='landtourpage',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_pdf', to='documents.customdocument'),
        ),
    ]
