# Generated by Django 5.2.6 on 2025-11-24 17:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_landtourpage_collect_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtourpage',
            name='inquiry_message',
            field=wagtail.fields.RichTextField(blank=True, help_text='If Collect Price is unchecked, or more specifically, if no prices to be collected, please write a message to show instead.', max_length=300, null=True, verbose_name='Inquiry Message'),
        ),
    ]
