# Generated by Django 5.2.6 on 2025-12-09 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("tours", "0029_alter_daytourpage_description_content_and_more"),
        ("wagtailimages", "0027_image_description"),
=======
        ('tours', '0029_alter_daytourpage_description_content_and_more'),
        ('wagtailimages', '0027_image_description'),
>>>>>>> cbb398c85844ebfd77d9a14aaa552cb88b5e7f01
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="daytourpage",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Leave blank to use the page's URL.",
                max_length=255,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="daytourpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Preview image",
            ),
        ),
        migrations.AddField(
            model_name="fulltourpage",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Leave blank to use the page's URL.",
                max_length=255,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="fulltourpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Preview image",
            ),
        ),
        migrations.AddField(
            model_name="landtourpage",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Leave blank to use the page's URL.",
                max_length=255,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="landtourpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Preview image",
            ),
        ),
        migrations.AddField(
            model_name="toursindexpage",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Leave blank to use the page's URL.",
                max_length=255,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="toursindexpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Preview image",
            ),
=======
            model_name='daytourpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='daytourpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image'),
        ),
        migrations.AddField(
            model_name='fulltourpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='fulltourpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image'),
        ),
        migrations.AddField(
            model_name='landtourpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='landtourpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image'),
        ),
        migrations.AddField(
            model_name='toursindexpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='toursindexpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image'),
>>>>>>> cbb398c85844ebfd77d9a14aaa552cb88b5e7f01
        ),
    ]
