# Generated by Django 5.2.6 on 2025-12-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0030_daytourpage_canonical_url_daytourpage_og_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytourpage',
            name='price_per_person',
        ),
    ]
