# Generated by Django 5.2.6 on 2025-11-26 17:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('content', 0), ('tour_teaser', 4), ('faq', 8), ('cta', 9)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h3', 'h4', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed']}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose any tour: Land, Full, or Day tour', 'page_type': ['tours.LandTourPage', 'tours.FullTourPage', 'tours.DayTourPage'], 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override tour name', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book this tour', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('tour', 1), ('custom_title', 2), ('cta_text', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('q', 5), ('a', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'template': 'streams/faq.html'}), 9: ('wagtail.blocks.StructBlock', [[('text', 5), ('button', 5)]], {'template': 'streams/cta.html'})}),
        ),
    ]
