# Generated by Django 5.2.6 on 2025-11-29 16:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogdetailpage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='sidebar',
            field=wagtail.fields.StreamField([('widget', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. On this page, Share, About the author', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('toc', 'Table of Contents (auto-generated)'), ('share', 'Share Buttons'), ('author', 'Author Card'), ('newsletter', 'Newsletter Signup'), ('related', 'Related Posts'), ('custom', 'Custom Content')], 'help_text': 'Auto TOC is smart – it reads H2/H3 from the article body'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Author name', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Travel Expert in Poland', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('widget_type', 1), ('content', 2), ('image', 3), ('name', 4), ('role', 5), ('social_twitter', 6), ('social_instagram', 6)]], {})}),
        ),
    ]
