# Generated by Django 5.2.6 on 2025-11-29 17:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogdetailpage_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='cover_page',
            field=wagtail.fields.StreamField([('swiper', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The main title.', 'max_length': 33, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'max_length': 40, 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link for the image. If provided, the image will be clickable.', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('basic', 'Basic Swiper'), ('collage', 'Collage Navigation'), ('coverflow', 'Coverflow (3D)'), ('framed', 'Framed Pictures'), ('thumbnail', 'Thumbnail Navigation')]}), 7: ('wagtail.blocks.StructBlock', [[('swiper_title', 0), ('images', 5), ('variations', 6)]], {})}, null=True),
        ),
    ]
