# Generated by Django 5.2.6 on 2025-11-29 17:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogindexpage_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='cover_page',
            field=wagtail.fields.StreamField([('FadeCarousel', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The main title.', 'max_length': 33, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'The subtitle.', 'max_length': 33, 'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'help_text': "Image height in 'rem' units.", 'verbose_name': 'Image Height'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'max_length': 40, 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link for the image. If provided, the image will be clickable.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('link', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('fade_title', 0), ('fade_subtitle', 1), ('height', 2), ('images', 7), ('search_bar', 8)]], {})}, null=True),
        ),
    ]
