# Generated by Django 5.2.6 on 2026-03-05 17:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogindexpage_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('content', 0), ('tour_teaser', 4), ('faq', 8), ('cta', 22)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h3', 'h4', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed']}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose any tour: Land, Full, or Day tour', 'page_type': ['tours.LandTourPage', 'tours.FullTourPage', 'tours.DayTourPage'], 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override tour name', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book this tour', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('tour', 1), ('custom_title', 2), ('cta_text', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Question', 'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Answer', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('question', 5), ('answer', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('item', 7)]], {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Top Side'), ('bottom', 'Bottom Side')], 'help_text': 'Text box background color'}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'This image will appear below the CTA', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Caption at the base of the image', 'max_length': 33, 'required': False}), 12: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'By checking the box, a Call To Action with buttons and a bullet point list will be available', 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('--yellow-100', 'White'), ('--yellow-dark-100', 'Black'), ('--yellow-dark-70', 'Brown'), ('--cyan-10', 'Cyan'), ('--cyan-dark-70', 'Dark Cyan'), ('--green2-dark-70', 'Dark Green'), ('--red-dark-60', 'Dark Red'), ('--yellow-dark-40', 'Dark Yellow'), ('gray', 'Gray'), ('--green2-10', 'Green'), ('--cyan-60', 'Sky Blue'), ('--yellow-dark-30', 'Sand'), ('--red-10', 'Red'), ('--red-dark-20', 'Red Blood'), ('--red-50', 'Pink'), ('--yellow-0', 'Yellow')], 'help_text': 'Text box background color'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'The main title.', 'max_length': 33, 'required': False}), 15: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Describe in detail your Call To Action', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text.', 'max_length': 33, 'required': False}), 17: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link to send the user by clicking the left button', 'required': False}), 18: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link to send the user by clicking the right button', 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Bullet point list element', 'max_length': 33, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('element', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('image_position', 9), ('image', 10), ('caption', 11), ('include_cta', 12), ('background_color', 13), ('cta_title', 14), ('cta_description', 15), ('button_1_text', 16), ('button_link_1', 17), ('button_2_text', 14), ('button_link_2', 18), ('list', 21)]], {})}),
        ),
    ]
