# Generated by Django 5.2.6 on 2025-12-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_accommodationsindexpage_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinpage',
            name='is_company_accom',
            field=models.BooleanField(default=False, help_text='If True, skip supplier  and go direct to payment (company-run accommodation).'),
        ),
        migrations.AlterField(
            model_name='campsitepage',
            name='is_company_accom',
            field=models.BooleanField(default=False, help_text='If True, skip supplier  and go direct to payment (company-run accommodation).'),
        ),
        migrations.AlterField(
            model_name='glampingpage',
            name='is_company_accom',
            field=models.BooleanField(default=False, help_text='If True, skip supplier  and go direct to payment (company-run accommodation).'),
        ),
        migrations.AlterField(
            model_name='hostelpage',
            name='is_company_accom',
            field=models.BooleanField(default=False, help_text='If True, skip supplier  and go direct to payment (company-run accommodation).'),
        ),
        migrations.AlterField(
            model_name='hotelroompage',
            name='is_company_accom',
            field=models.BooleanField(default=False, help_text='If True, skip supplier  and go direct to payment (company-run accommodation).'),
        ),
    ]
