# Generated by Django 5.2.6 on 2025-11-06 00:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("banner_title", models.CharField(max_length=100, null=True)),
                (
                    "banner_subtitle",
                    wagtail.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "carousel",
                    wagtail.fields.StreamField(
                        [("carousel", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title for the image", "required": False},
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional caption for the image",
                                    "max_length": 40,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Optional link for the image. If provided, the image will be clickable.",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("caption", 2), ("link", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.ListBlock", (4,), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("caption", 0), ("carousel", 5)]],
                                {},
                            ),
                        },
                        help_text="Add images to the carousel. Each image can have an optional caption and link.",
                        null=True,
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("explore_block", 10),
                            ("video_text_content", 15),
                            ("text_band", 20),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Add title i.e.: Explore this awesome tour",
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "56px x 56px", "required": True},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Subtitle below the top left icon",
                                    "max_length": 60,
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"max_length": 300, "required": True},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Subtitle below the top right icon",
                                    "max_length": 60,
                                    "required": True,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Subtitle below the bottom left icon",
                                    "max_length": 60,
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Subtitle below the bottom right icon",
                                    "max_length": 60,
                                    "required": True,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_1", 2),
                                        ("subtitle_1", 3),
                                        ("text_1", 4),
                                        ("icon_2", 2),
                                        ("subtitle_2", 5),
                                        ("text_2", 4),
                                        ("icon_3", 2),
                                        ("subtitle_3", 6),
                                        ("text_3", 4),
                                        ("icon_4", 2),
                                        ("subtitle_4", 7),
                                        ("text_4", 4),
                                    ]
                                ],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("image", 1), ("body", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Youtube EMBED link. i.e.: https://www.youtube.com/embed/_lw9r4T1PEc?si=43WbnkOeB1LsVgwL. Go to Share and click on <>EMBED",
                                    "required": True,
                                },
                            ),
                            12: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "100px x 100px", "required": True},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_1", 12),
                                        ("subtitle_1", 3),
                                        ("text_1", 4),
                                        ("icon_2", 12),
                                        ("subtitle_2", 5),
                                        ("text_2", 4),
                                    ]
                                ],
                                {},
                            ),
                            14: ("wagtail.blocks.ListBlock", (13,), {}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("video", 11), ("body", 14)]],
                                {},
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 36, "required": True},
                            ),
                            17: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": True,
                                },
                            ),
                            18: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            19: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("--cyan-dark-10", "Cyan"),
                                        ("--yellow-dark-20", "Yellow"),
                                        ("--red-dark-10", "Red"),
                                        ("--green2-dark-20", "Green"),
                                        ("--yellow-dark-100", "Black"),
                                    ]
                                },
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("band_title", 16),
                                        ("textbox_1", 17),
                                        ("textbox_2", 17),
                                        ("background_image", 18),
                                        ("background_color", 19),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "banner_cta",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose a page to link to from the banner button.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "banner_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
