# Generated by Django 5.2.6 on 2025-11-11 17:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('carousel', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Carousel main title', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Carousel subtitle above the title (optional)', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'max_length': 40, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link for the image. If provided, the image will be clickable.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('link', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'If True, Carousel will have available the Search Bar', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('carousel_title', 0), ('carousel_subtitle', 1), ('carousel', 6), ('search_bar', 7)]], {})}, help_text='Add images to the carousel. Each image can have an optional caption and link.', null=True),
        ),
    ]
