# Generated by Django 5.2.6 on 2025-09-21 02:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_home_carousel_alter_homepage_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_carousel',
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('image', 0), ('caption', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'required': False})}),
        ),
    ]
