# Generated by Django 5.2.6 on 2025-09-24 16:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_explore_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='explore_content',
            field=wagtail.fields.StreamField([('explore_block', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': 'color', 'help_text': 'Add title i.e.: Explore this awesome tour', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '56px x 56px', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top left icon', 'max_length': 60, 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'max_length': 300, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top right icon', 'max_length': 60, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom left icon', 'max_length': 60, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom right icon', 'max_length': 60, 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('icon_1', 2), ('subtitle_1', 3), ('text_1', 4), ('icon_2', 2), ('subtitle_2', 5), ('text_2', 4), ('icon_3', 2), ('subtitle_3', 6), ('text_3', 4), ('icon_4', 2), ('subtitle_4', 7), ('text_4', 4)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1), ('body', 9)]], {})}, null=True),
        ),
    ]
