# Generated by Django 5.2.6 on 2025-11-22 00:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('carousel', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'YouTube ID', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption overlay', 'max_length': 100, 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link (makes whole slide clickable)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('video_url', 3), ('caption', 4), ('link', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'min_num': 1}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'form_classname': 'DEPRECATED_old_carousel_field', 'required': False}), 12: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('carousel_title', 0), ('carousel_subtitle', 1), ('slides', 7), ('carousel', 11), ('search_bar', 12)]], {})}, help_text='Add images to the carousel. Each image can have an optional caption and link.', null=True),
        ),
    ]
