# Generated by Django 5.2.6 on 2025-10-03 17:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_homepage_explore_content_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('cards', 4), ('explore_block', 14), ('video_text_content', 19)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['color'], 'help_text': 'Add title i.e.: Explore this awesome tour', 'required': True}), 1: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Estimated price', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Estimated. IVA not included', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'i.e.: Book, Buy, Contact', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('sub_title', 0), ('card_description', 0), ('price', 1), ('price_subtext', 2), ('button_title', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '56px x 56px', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top left icon', 'max_length': 60, 'required': True}), 8: ('wagtail.blocks.RichTextBlock', (), {'max_length': 300, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top right icon', 'max_length': 60, 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom left icon', 'max_length': 60, 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom right icon', 'max_length': 60, 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('icon_1', 6), ('subtitle_1', 7), ('text_1', 8), ('icon_2', 6), ('subtitle_2', 9), ('text_2', 8), ('icon_3', 6), ('subtitle_3', 10), ('text_3', 8), ('icon_4', 6), ('subtitle_4', 11), ('text_4', 8)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 5), ('body', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'Youtube EMBED link. i.e.: https://www.youtube.com/embed/_lw9r4T1PEc?si=43WbnkOeB1LsVgwL. Go to Share and click on <>EMBED', 'required': True}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '100px x 100px', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('icon_1', 16), ('subtitle_1', 7), ('text_1', 8), ('icon_2', 16), ('subtitle_2', 9), ('text_2', 8)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 0), ('video', 15), ('body', 18)]], {})}, null=True),
        ),
    ]
