# Generated by Django 5.2.6 on 2025-11-22 23:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_homepage_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('carousel', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption overlay', 'max_length': 100, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link (makes whole slide clickable)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('link', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'min_num': 1}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 8: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 7), ('link', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'form_classname': 'DEPRECATED_old_carousel_field', 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('carousel_title', 0), ('carousel_subtitle', 1), ('slides', 6), ('carousel', 10), ('search_bar', 11)]], {})}, help_text='Add images to the carousel. Each image can have an optional caption and link.', null=True),
        ),
    ]
