# Generated by Django 5.2.6 on 2025-10-03 20:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('cards', 11), ('explore_block', 21), ('video_text_content', 26)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Product image', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['color'], 'help_text': 'Add title i.e.: Explore this awesome tour', 'required': True}), 2: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Estimated price', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Estimated. IVA not included', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'i.e.: Book, Buy, Contact', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Yellow Tag'}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Red Tag'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Country tag'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Destination inside the country tag'}), 9: ('wagtail.blocks.StructBlock', [[('top_tag_1', 5), ('top_tag_2', 6), ('center_right_tag_1', 7), ('center_right_tag_2', 8)]], {'max_num': 1}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('sub_title', 1), ('card_description', 1), ('price', 2), ('price_subtext', 3), ('button_title', 4), ('tags', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '56px x 56px', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top left icon', 'max_length': 60, 'required': True}), 15: ('wagtail.blocks.RichTextBlock', (), {'max_length': 300, 'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top right icon', 'max_length': 60, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom left icon', 'max_length': 60, 'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom right icon', 'max_length': 60, 'required': True}), 19: ('wagtail.blocks.StructBlock', [[('icon_1', 13), ('subtitle_1', 14), ('text_1', 15), ('icon_2', 13), ('subtitle_2', 16), ('text_2', 15), ('icon_3', 13), ('subtitle_3', 17), ('text_3', 15), ('icon_4', 13), ('subtitle_4', 18), ('text_4', 15)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('title', 1), ('image', 12), ('body', 20)]], {}), 22: ('wagtail.blocks.URLBlock', (), {'help_text': 'Youtube EMBED link. i.e.: https://www.youtube.com/embed/_lw9r4T1PEc?si=43WbnkOeB1LsVgwL. Go to Share and click on <>EMBED', 'required': True}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '100px x 100px', 'required': True}), 24: ('wagtail.blocks.StructBlock', [[('icon_1', 23), ('subtitle_1', 14), ('text_1', 15), ('icon_2', 23), ('subtitle_2', 16), ('text_2', 15)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('title', 1), ('video', 22), ('body', 25)]], {})}, null=True),
        ),
    ]
