# Generated by Django 5.2.6 on 2025-10-03 20:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('cards', 12), ('explore_block', 22), ('video_text_content', 27)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Product image', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'features': ['color'], 'help_text': 'Add title i.e.: Explore this awesome tour', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['color'], 'help_text': 'Add title i.e.: Explore this awesome tour', 'required': True}), 3: ('wagtail.blocks.FloatBlock', (), {'help_text': 'Estimated price', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Estimated. IVA not included', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'i.e.: Book, Buy, Contact', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Yellow Tag'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Red Tag'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Country tag'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Destination inside the country tag'}), 10: ('wagtail.blocks.StructBlock', [[('top_tag_1', 6), ('top_tag_2', 7), ('center_right_tag_1', 8), ('center_right_tag_2', 9)]], {'max_num': 1}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('sub_title', 2), ('card_description', 2), ('price', 3), ('price_subtext', 4), ('button_title', 5), ('tags', 11)]], {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '56px x 56px', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top left icon', 'max_length': 60, 'required': True}), 16: ('wagtail.blocks.RichTextBlock', (), {'max_length': 300, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top right icon', 'max_length': 60, 'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom left icon', 'max_length': 60, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom right icon', 'max_length': 60, 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('icon_1', 14), ('subtitle_1', 15), ('text_1', 16), ('icon_2', 14), ('subtitle_2', 17), ('text_2', 16), ('icon_3', 14), ('subtitle_3', 18), ('text_3', 16), ('icon_4', 14), ('subtitle_4', 19), ('text_4', 16)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('title', 2), ('image', 13), ('body', 21)]], {}), 23: ('wagtail.blocks.URLBlock', (), {'help_text': 'Youtube EMBED link. i.e.: https://www.youtube.com/embed/_lw9r4T1PEc?si=43WbnkOeB1LsVgwL. Go to Share and click on <>EMBED', 'required': True}), 24: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '100px x 100px', 'required': True}), 25: ('wagtail.blocks.StructBlock', [[('icon_1', 24), ('subtitle_1', 15), ('text_1', 16), ('icon_2', 24), ('subtitle_2', 17), ('text_2', 16)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('title', 2), ('video', 23), ('body', 26)]], {})}, null=True),
        ),
    ]
