# Generated by Django 5.2.6 on 2025-10-04 00:02

import streams.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_content'),
    ]

operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField(
                [
                    ('cards', 'streams.blocks.HomeCardsBlock'),
                    ('explore_block', 'streams.blocks.ExploreBlock'),
                    ('video_text_content', 'streams.blocks.Video_Text_Block'),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
