# Generated by Django 5.2.6 on 2025-11-25 02:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='carousel',
            field=wagtail.fields.StreamField([('carousel', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The main title.', 'max_length': 33, 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'max_length': 40, 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link for the image. If provided, the image will be clickable.', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('fade_title', 0), ('images', 5)]], {})}, help_text='Add images to the fade carousel. Each image can have an optional caption and link.', null=True),
        ),
    ]
