# Generated by Django 5.2.6 on 2025-09-24 03:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('explore_block', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add title i.e.: Explore this awesome tour', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '56px x 56px', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the icon', 'max_length': 40, 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('icon', 1), ('subtitle', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 5)]], {})}, null=True),
        ),
    ]
