# Generated by Django 5.2.6 on 2025-10-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'New Page', 'verbose_name_plural': 'New Pages'},
        ),
    ]
