# Generated by Django 5.2.6 on 2025-10-13 17:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0008_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('explore_block', 10), ('carousel', 17), ('text_band', 22)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['color'], 'help_text': 'Add title i.e.: Explore this awesome tour', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '56px x 56px', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top left icon', 'max_length': 60, 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'max_length': 300, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the top right icon', 'max_length': 60, 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom left icon', 'max_length': 60, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtitle below the bottom right icon', 'max_length': 60, 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('icon_1', 2), ('subtitle_1', 3), ('text_1', 4), ('icon_2', 2), ('subtitle_2', 5), ('text_2', 4), ('icon_3', 2), ('subtitle_3', 6), ('text_3', 4), ('icon_4', 2), ('subtitle_4', 7), ('text_4', 4)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1), ('body', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for the image', 'required': False}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'max_length': 40, 'required': False}), 14: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link for the image. If provided, the image will be clickable.', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('image', 12), ('caption', 13), ('link', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('caption', 11), ('carousel', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 36, 'required': True}), 19: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('--cyan-dark-10', 'Cyan'), ('--yellow-dark-20', 'Yellow'), ('--red-dark-10', 'Red'), ('--green2-dark-20', 'Green'), ('--yellow-dark-100', 'Black')]}), 22: ('wagtail.blocks.StructBlock', [[('band_title', 18), ('textbox_1', 19), ('textbox_2', 19), ('cover_image', 20), ('background_color', 21)]], {})}, null=True),
        ),
    ]
