# Generated by Django 5.2.6 on 2025-11-15 03:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flex", "0009_alter_flexpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("explore_block", 10),
                    ("text_band", 16),
                    ("flex_images", 20),
                    ("video_text_block", 25),
                    ("cta_2B", 39),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add title i.e.: Explore this awesome tour",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "56px x 56px", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subtitle below the top left icon",
                            "max_length": 60,
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"max_length": 300, "required": True},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subtitle below the top right icon",
                            "max_length": 60,
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subtitle below the bottom left icon",
                            "max_length": 60,
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subtitle below the bottom right icon",
                            "max_length": 60,
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_1", 2),
                                ("subtitle_1", 3),
                                ("text_1", 4),
                                ("icon_2", 2),
                                ("subtitle_2", 5),
                                ("text_2", 4),
                                ("icon_3", 2),
                                ("subtitle_3", 6),
                                ("text_3", 4),
                                ("icon_4", 2),
                                ("subtitle_4", 7),
                                ("text_4", 4),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("image", 1), ("body", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 36, "required": False},
                    ),
                    12: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    13: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("--cyan-60", "Sky Blue"),
                                ("--cyan-10", "Cyan"),
                                ("--cyan-dark-70", "Dark Cyan"),
                                ("--yellow-dark-30", "Sand"),
                                ("--yellow-0", "Yellow"),
                                ("--yellow-dark-40", "Dark Yellow"),
                                ("--yellow-dark-70", "Brown"),
                                ("--red-10", "Red"),
                                ("--red-dark-20", "Red Blood"),
                                ("--red-dark-60", "Dark Red"),
                                ("--red-50", "Pink"),
                                ("--green2-10", "Green"),
                                ("--green2-dark-70", "Dark Green"),
                                ("--yellow-dark-100", "Black"),
                                ("gray", "Gray"),
                                ("--yellow-100", "White"),
                            ]
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "If checked, all social links configured in admin/settings will render.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("band_title", 11),
                                ("textbox_1", 12),
                                ("textbox_2", 12),
                                ("background_image", 13),
                                ("background_color", 14),
                                ("social_media_icon", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption",
                            "max_length": 300,
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("caption", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {}),
                    20: ("wagtail.blocks.StructBlock", [[("image_caption", 19)]], {}),
                    21: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Youtube EMBED link. i.e.: https://www.youtube.com/embed/_lw9r4T1PEc?si=43WbnkOeB1LsVgwL. Go to Share and click on <>EMBED",
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "100px x 100px", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_1", 22),
                                ("subtitle_1", 3),
                                ("text_1", 4),
                                ("icon_2", 22),
                                ("subtitle_2", 5),
                                ("text_2", 4),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("video", 21), ("body", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top Side"), ("bottom", "Bottom Side")],
                            "help_text": "Text box background color",
                        },
                    ),
                    27: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "This image will appear below the CTA",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Caption at the base of the image",
                            "max_length": 33,
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "By checking the box, a Call To Action with buttons and a bullet point list will be available",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("--cyan-60", "Sky Blue"),
                                ("--cyan-10", "Cyan"),
                                ("--cyan-dark-70", "Dark Cyan"),
                                ("--yellow-dark-30", "Sand"),
                                ("--yellow-0", "Yellow"),
                                ("--yellow-dark-40", "Dark Yellow"),
                                ("--yellow-dark-70", "Brown"),
                                ("--red-10", "Red"),
                                ("--red-dark-20", "Red Blood"),
                                ("--red-dark-60", "Dark Red"),
                                ("--red-50", "Pink"),
                                ("--green2-10", "Green"),
                                ("--green2-dark-70", "Dark Green"),
                                ("--yellow-dark-100", "Black"),
                                ("gray", "Gray"),
                                ("--yellow-100", "White"),
                            ],
                            "help_text": "Text box background color",
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The main title.",
                            "max_length": 33,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Describe in detail your Call To Action",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text.",
                            "max_length": 33,
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Optional link to send the user by clicking the left button",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Optional link to send the user by clicking the right button",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Bullet point list element",
                            "max_length": 33,
                            "required": False,
                        },
                    ),
                    37: ("wagtail.blocks.StructBlock", [[("element", 36)]], {}),
                    38: ("wagtail.blocks.ListBlock", (37,), {}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 26),
                                ("image", 27),
                                ("caption", 28),
                                ("include_cta", 29),
                                ("background_color", 30),
                                ("cta_title", 31),
                                ("cta_description", 32),
                                ("button_1_text", 33),
                                ("button_link_1", 34),
                                ("button_2_text", 31),
                                ("button_link_2", 35),
                                ("list", 38),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="\n        This is the page's body. Use the different blocks by clicking the Plus (+) icon. Carousel Block to add Cover Images.\n        More than one images will incurred in the Slide effect. Text Band will add a text section with color background that\n        occupies the whole width of the page. Explore Block will add a dedicated section to expand in detail any product, announce or service.\n        More blocks are currently being developed. If you need a specific design, please contact developer and show them the design you would like\n        to see implemented. Anything is possible!.\n        ",
                null=True,
            ),
        ),
    ]
