# Generated by Django 5.2.6 on 2025-09-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_tw', models.URLField(blank=True, null=True, verbose_name='X URL')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('tik_tok', models.URLField(blank=True, null=True, verbose_name='TikTok URL')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube URL')),
            ],
            options={
                'verbose_name': 'Footer Links',
            },
        ),
    ]
