# Generated by Django 5.2.6 on 2025-11-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_tw", models.URLField(blank=True, null=True, verbose_name="X URL")),
                (
                    "facebook",
                    models.URLField(blank=True, null=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Instagram URL"
                    ),
                ),
                (
                    "tik_tok",
                    models.URLField(blank=True, null=True, verbose_name="TikTok URL"),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, null=True, verbose_name="YouTube URL"),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True,
                        max_length=310,
                        null=True,
                        verbose_name="WhatsApp URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Links",
            },
        ),
        migrations.CreateModel(
            name="BrandSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Milano Travel", max_length=300),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Company Logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Settings",
            },
        ),
    ]
