# Generated by Django 5.2.6 on 2025-09-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinks',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp URL'),
        ),
    ]
