# Generated by Django 5.2.6 on 2025-11-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='telephone',
            field=models.CharField(default='+593', max_length=20),
        ),
    ]
