# Generated by Django 5.2.6 on 2025-10-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandsettings",
            name="company_name",
            field=models.CharField(default="Milano Travel", max_length=300),
        ),
    ]
