# Generated by Django 5.2.6 on 2025-11-14 02:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_brandsettings_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='address',
            field=wagtail.fields.RichTextField(blank=True, default='Honorato Vasquez', null=True),
        ),
    ]
