# Generated by Django 5.2.6 on 2025-11-16 20:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_brandsettings_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='search_suggestion',
            field=wagtail.fields.RichTextField(blank=True, default="Don't know what to look for? Try >>", null=True),
        ),
    ]
