# Generated by Django 5.2.6 on 2025-10-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_brandsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlinks',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=310, null=True, verbose_name='WhatsApp URL'),
        ),
    ]
