# Generated by Django 5.2.6 on 2025-11-21 15:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_brandsettings_search_suggestion'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='footer_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Footer Background'),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='search_suggestion',
            field=wagtail.fields.RichTextField(blank=True, default="Don't know what to look for? Try >>[Insert Link]", null=True),
        ),
    ]
