# Generated by Django 5.2.6 on 2025-11-26 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('site_settings', '0007_sponsors_badges_sponsorlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsettings',
            name='footer_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Footer Background'),
        ),
        migrations.AlterField(
            model_name='brandsettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='sponsorlogo',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
