# Generated by Django 5.2.6 on 2025-11-06 00:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., EUR, GBP)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "rate_to_usd",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Exchange rate relative to 1 USD",
                        max_digits=10,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When the rate was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prop_id",
                    models.CharField(
                        editable=False,
                        help_text="Proposal code so the user can track status.",
                        max_length=9,
                        null=True,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                (
                    "customer_address",
                    models.TextField(
                        blank=True, help_text="Optional address for records"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional customer requests or notes"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, help_text="e.g., +593-99-123-4567", max_length=20
                    ),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                ("object_id", models.PositiveIntegerField()),
                ("number_of_adults", models.PositiveIntegerField(default=1)),
                ("number_of_children", models.PositiveIntegerField(default=0)),
                ("number_of_infants", models.PositiveIntegerField(default=0)),
                (
                    "children_ages",
                    models.JSONField(
                        blank=True, default=list, help_text="List of ages for children"
                    ),
                ),
                ("room_config", models.JSONField(default=dict)),
                (
                    "selected_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Selected room configuration from pricing options.",
                    ),
                ),
                (
                    "travel_date",
                    models.DateField(help_text="Preferred start date for the tour"),
                ),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "supplier_email",
                    models.EmailField(
                        blank=True, help_text="Supplier contact email", max_length=254
                    ),
                ),
                (
                    "payment_link",
                    models.URLField(blank=True, help_text="Payment link for customer"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency used for pricing (ISO 4217 code)",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_SUPPLIER", "Pending Supplier Confirmation"),
                            ("PENDING_INTERNAL", "Pending Internal Confirmation"),
                            ("SUPPLIER_CONFIRMED", "Supplier Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING_SUPPLIER",
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of tour (Full, Land, or Day).",
                        limit_choices_to={
                            "model__in": ("fulltourpage", "landtourpage", "daytourpage")
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created the proposal. Defaults to MTWEB for non-authenticated users.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_id",
                    models.CharField(
                        editable=False,
                        help_text="Booking code so the user can track status.",
                        max_length=9,
                        null=True,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                (
                    "customer_address",
                    models.TextField(
                        blank=True, help_text="Optional address for records"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional customer requests or notes"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, help_text="e.g., +593-99-123-4567", max_length=20
                    ),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                ("object_id", models.PositiveIntegerField()),
                ("number_of_adults", models.PositiveIntegerField(default=1)),
                ("number_of_children", models.PositiveIntegerField(default=0)),
                (
                    "children_ages",
                    models.JSONField(
                        blank=True, default=list, help_text="List of ages for children"
                    ),
                ),
                (
                    "booking_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "travel_date",
                    models.DateField(help_text="Preferred start date for the tour"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("UNPAID", "Unpaid"), ("PAID", "Paid")],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_SUPPLIER", "Pending Supplier Confirmation"),
                            ("PENDING_INTERNAL", "Pending Internal Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("configuration_details", models.JSONField(default=dict)),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency used for pricing (ISO 4217 code)",
                        max_length=3,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of tour (Full, Land, or Day).",
                        limit_choices_to={
                            "model__in": ("fulltourpage", "landtourpage", "daytourpage")
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created the proposal. Defaults to MTWEB for non-authenticated users.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.proposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_date"],
            },
        ),
        migrations.CreateModel(
            name="ProposalConfirmationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=32, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmation_tokens",
                        to="bookings.proposal",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["content_type", "object_id", "travel_date", "status"],
                name="bookings_pr_content_8139df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["content_type", "object_id", "travel_date", "status"],
                name="bookings_bo_content_011b0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proposalconfirmationtoken",
            index=models.Index(fields=["token"], name="bookings_pr_token_54317d_idx"),
        ),
    ]
