# Generated by Django 5.2.6 on 2025-10-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='proposal',
            name='bookings_pr_content_8139df_idx',
        ),
        migrations.AddField(
            model_name='proposal',
            name='selected_config',
            field=models.JSONField(blank=True, default=dict, help_text='Selected room configuration from pricing options.'),
        ),
    ]
