# Generated by Django 5.2.6 on 2025-12-09 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="content_type",
            field=models.ForeignKey(
                help_text="Type of tour (Full, Land, or Day) or Accommodation.",
                limit_choices_to={
                    "model__in": ("fulltourpage", "landtourpage", "daytourpage", "")
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
