# Generated by Django 5.2.6 on 2025-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_proposal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='number_of_infants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
