# Generated by Django 5.2.6 on 2025-12-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveSmallIntegerField()),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('child_ages', models.JSONField(blank=True, default=list)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('SUPPLIER_NOTIFIED', 'Supplier Notified'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20)),
                ('supplier_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='bookings_ac_content_43c704_idx'), models.Index(fields=['check_in', 'check_out'], name='bookings_ac_check_i_ff857b_idx')],
            },
        ),
    ]
