# Generated by Django 5.2.6 on 2025-10-29 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_proposal_number_of_infants'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['content_type', 'object_id', 'travel_date', 'status'], name='bookings_pr_content_8139df_idx'),
        ),
    ]
