# Generated by Django 5.2.6 on 2025-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_accommodationbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationbooking',
            name='child_ages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='accommodationbooking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
