# Generated by Django 5.2.6 on 2025-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_proposal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_SUPPLIER', 'Pending Supplier Confirmation'), ('PENDING_INTERNAL', 'Pending Internal Confirmation'), ('SUPPLIER_CONFIRMED', 'Supplier Confirmed'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('PENDING_SUPPLIER', 'Pending Supplier Confirmation'), ('PENDING_INTERNAL', 'Pending Internal Confirmation'), ('SUPPLIER_CONFIRMED', 'Supplier Confirmed'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING_SUPPLIER', max_length=20),
        ),
    ]
