# Generated by Django 5.2.6 on 2026-01-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_accommodationbooking_child_ages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_infants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
