# Generated by Django 5.2.6 on 2026-01-14 15:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_number_of_infants'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Discount amount actually applied (in proposal currency)', max_digits=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='eferral_code_used',
            field=models.CharField(blank=True, editable=False, help_text='Referral code used during creation (if any)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='promo_code_used',
            field=models.CharField(blank=True, editable=False, help_text='Discount/promo code used during creation (if any)', max_length=16, null=True),
        ),
    ]
