# Generated by Django 5.2.6 on 2026-01-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_proposal_discount_amount_proposal_eferral_code_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='eferral_code_used',
            new_name='referral_code_used',
        ),
    ]
