# Generated by Django 5.2.6 on 2026-01-15 16:50

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_rename_eferral_code_used_proposal_referral_code_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbooking',
            name='country',
            field=django_countries.fields.CountryField(default='do', max_length=2),
            preserve_default=False,
        ),
    ]
