# Generated by Django 5.2.6 on 2026-01-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_accommodationbooking_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationbooking',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
