# Generated by Django 5.2.6 on 2026-01-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_accommodationbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbooking',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='After this, pending bookings auto-expire if unpaid', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='After this time pending proposals auto-expire if not paid', null=True),
        ),
        migrations.AlterField(
            model_name='accommodationbooking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('SUPPLIER_NOTIFIED', 'Supplier Notified'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired – unpaid after time limit')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('PENDING_SUPPLIER', 'Pending Supplier Confirmation'), ('PENDING_INTERNAL', 'Pending Internal Confirmation'), ('SUPPLIER_CONFIRMED', 'Supplier Confirmed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired – time limit reached'), ('CANCELLED', 'Cancelled'), ('PAID', 'Paid')], default='PENDING_SUPPLIER', max_length=20),
        ),
    ]
